version: "3"
services:
  back:
    image: ghcr.io/ilyakachnov/promocodes:latest
    container_name: promocodes
    ports:
      - "8081:8081"
  api:
    image: ghcr.io/ilyakachnov/telegram-api:latest
    container_name: telegram-api
    ports:
      - "8082:8082"
#  db:
#    image: 'postgres:latest'
#    container_name: promo_db
#    ports:
#      - "5432:5432"
#    volumes:
##      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
#      - postgres-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=passw0rd