version: "3"
services:
  back:
    image: ghcr.io/ilyakachnov/promocodes:latest
    container_name: promocodes
    depends_on:
      - postgres
    ports:
      - "8081:8081"
  db:
    image: 'postgres:latest'
    container_name: promo_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd