server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: passw0rd
    url: jdbc:postgresql://localhost:5432/promo_codes
    username: postgres
service:
  scheduler:
    cron: "0 0 4 * * ?"
logging:
  level:
    root: info

gpt:
  auth-token: