server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: passw0rd
    url: jdbc:postgresql://79.174.82.98:5432/postgres
    username: postgres
  liquibase:
    change-log: classpath:liquibase/changelog.xml
service:
  scheduler:
    cron: "0 0 4 * * ?"
  youtube:
    key: key
logging:
  level:
    root: info

gpt:
  auth-token: ${GPT_TOKEN}