server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: <db_password>
    url: jdbc:postgresql://79.174.82.98:5432/promocodes
    username: postgres
  liquibase:
    change-log: classpath:liquibase/changelog.xml
service:
  scheduler:
    cron: "0 0 4 * * ?"
  youtube:
    key: <youtube_api_key>
  processing:
    number-of-videos: 3
logging:
  level:
    root: info
  file:
    path: logs
gpt:
  auth-token: <gpt_api>