# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package Promocodes

on:
  release:
    paths:
      - 'promocodes/promocodes/**'
env:
  IMAGE_NAME: promocodes
  OWNER: '${{ github.repository_owner }}'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: promocodes
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
    - name: build the docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: 'promocodes/promocodes/Dockerfile'
        push: false
    - name: set lower case owner name
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
    - name: Tag & publish to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/$OWNER_LC/$IMAGE_NAME
        VERSION=latest
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
