name: Telegram-API pipeline
on:
  push:
    branches:
      - main
      - master
    paths:
      - telegram-api/**
      - .github/workflows/**
env:
  IMAGE_NAME: telegram-api
  OWNER: '${{ github.repository_owner }}'
  VERSION: latest
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telegram-api
    permissions:
      contents: read
      packages: write
    name: Build image
    steps:
      - uses: actions/checkout@v4
      - name: Update env vars
        run: |
          sed -i 's/<bot_token>/${{ secrets.BOT_TOKEN }}/' src/main/resources/application.yaml
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Extract project version
        id: extract_version
        run: |
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
      - name: login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: telegram-api/
          dockerfile: telegram-api/Dockerfile
          push: false
          tags: telegram-api:latest
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      - name: Tag & publish to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/$OWNER_LC/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: create docker compose config
        run: |
          cat docker-compose-api.yml | envsubst > docker-compose-secret.yml
      - name: copy docker compose config
        run: scp docker-compose-secret.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:docker-compose-api.yml
      - name: connect and pull

        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF 
          docker-compose -f docker-compose-api.yml down 
          docker system prune -a -f 
          docker-compose -f docker-compose-api.yml pull 
          docker-compose -f docker-compose-api.yml up -d
          EOF
      - name: cleanup config
        if: always()
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm docker-compose-api.yml"
      - name: cleanup keys
        if: always()
        run: rm -rf ~/.ssh docker-compose-secret.yml
