server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: <db_password>
    url: jdbc:postgresql://79.174.82.98:5432/promocodes
    username: postgres
telegram:
  api-url: https://api.telegram.org/
  webhook-path: "http://79.174.82.98:8082"
  bot-name: "Promocode_App_Bot"
  bot-token: <bot_token>