server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: passw0rd
    url: jdbc:postgresql://localhost:5432/promo_codes
    username: postgres
telegram:
  api-url: https://api.telegram.org/
  webhook-path: "https://fc75-46-242-15-119.ngrok-free.app"
  bot-name: "Promocode_App_Bot"
  bot-token: ""